### ISSUE TITLE
Repo for trimmer capacitors

### ISSUE THREAD

**Issue by hackscribble** [KiCad/Capacitors_SMD.pretty#15]
I want to add footprints for some trimmer capacitors, SMD and THT.

Should these be put in this repo and `Capacitors_THT.pretty` or should there a new repo `Capacitors_Variable.pretty`, in the same way that there is a `Potentiometers.pretty`?

Thanks

**Comment by SchrodingersGat** [comment]
I think it should be sufficient to split them into the `_SMD` and `_THT` repos that already exist.

**Comment by hackscribble** [comment]
Thanks @SchrodingersGat Will do.

**Comment by jkriege2** [comment]
Hmmm ... I think as there is a repo for PotMeters, we should also have one for TrimCaps (I would not split it into SMD+THT though) ...

JAN
