### ISSUE TITLE
capacitor F.Fab REF** should be inside component box

### ISSUE THREAD

**Issue by jensenr30** [KiCad/Capacitors_SMD.pretty#18]
Currently, all of the SMD capacitors in this library have their F.Fab **REF**** *outside* their F.Fab boxes:
![image](https://user-images.githubusercontent.com/3083835/28394666-46d916c4-6cb4-11e7-9910-3ce2a8312e1b.png)
However, all of the SMD resistors have their **REF**** *inside* their boxes:
![image](https://user-images.githubusercontent.com/3083835/28394750-e2c66050-6cb4-11e7-81f7-22e4d3beeecb.png)

I think it would be great to move the **REF**** inside the box for all capacitors in this library.

I am willing to go through the work of doing this. I have already forked a repository.
I am waiting for feedback from the people who manage this repo. Does this sound good to other people as well? If I get positive responses, I will go ahead with the work and then make a pull-request.

**Comment by SchrodingersGat** [comment]
As with the inductors, this would be a welcome fix. Thanks.

**Comment by Shackmeister** [comment]
Isnt these caps scripted? If not they should be :)

**Comment by jensenr30** [comment]
@Shackmeister what do you mean by scripted?
Forgive me, I'm new to kicad. Just learning.
FYI:
I'm planning on editing all of the SMD caps and inductors systematically with find and replace using my test editor. Then I will check the results using the kicad footprint browser. If the results look good, I will commit and do a pull request.

**Comment by Shackmeister** [comment]
We have a pretty strong python script framework for generating a lot of footprints this can be much faster and easier to maintain compared to manually editing everything :) please have a look here : https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts

**Comment by jensenr30** [comment]
I updated my caps, inductors, and resistors. Man, this is *way* more readable.  :3
## Before
![image](https://user-images.githubusercontent.com/3083835/28397260-1ec9ba46-6cc6-11e7-8ae2-ebb1f7a4cbd6.png)
## After
![image](https://user-images.githubusercontent.com/3083835/28397317-7df3ff72-6cc6-11e7-970e-111b73b39bde.png)
I'll be creating the pull requests for Inductors_SMD.pretty and Resistors_SMD.pretty momentarily...

**Comment by pointhi** [comment]
such simple devices already have python support, and would only need little changes to the script to correctly output the F.Fab REF**

https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Resistors_SMD/smd_chip_resistors_smd.csv

**Comment by SchrodingersGat** [comment]
@pointhi are the R / L / C SMT chip devices already scripted in the library, or does the script exist separately?

**Comment by pointhi** [comment]
I don't think so. Nobody filled the .csv files with the required values yet.

**Comment by SchrodingersGat** [comment]
@jensenr30 do you feel like delving into the world of python scripting? The script is already written, the values just need to be added.

If you are willing to transcribe the current footprint data into the script, and then adjust the RefDes position (in the script) then this will mean that any subsequent changes can be made to the script, rather than to each footprint individually.

**Comment by jensenr30** [comment]
@SchrodingersGat 
Yes and no. However, I will do it. I'll take a second (closer) look at the python scripts and see what I can do. I'll probably love it.
I'll try to make some time to do this.

**Comment by SchrodingersGat** [comment]
It would be much appreciated @jensenr30 :)

Feel free to ask questions regarding the scripts or the parameters. Myself, @jkriege2 or @pointhi are probably your best points of contact on this.

**Comment by evanshultz** [comment]
@jensenr30 
I'm ashamed to admit this, but here goes...

I should be familiar and comfortable using the Python scripts, but I'm not. The Python code is easy to understand and I could certainly write more, but I wasn't able to run the scripts to generate footprints. Some of the framework appears to be written with *NIX in mind, while I only use Windows. If they run on Windows, and you figure it out, please let me know. There's a lot I could and should be doing with script-generated footprints.

**Comment by jensenr30** [comment]
@evanshultz Thanks for the heads up!!!
I will take a look at this hopefully in about 8 hours.
I am running Windows at the moment as well.
Pray tell, how did you determine that the python scripts were written with *NIX in mind? Do they use *NIX-specific commands or something like that?

**Comment by evanshultz** [comment]
https://github.com/pointhi/kicad-footprint-generator uses a file named `manage.sh`, which is for a *NIX shell. This may not mean it doesn't run on Windows, but some other framework may be required to execute the scripts. Or use [WSL](https://github.com/Microsoft/BashOnWindows).

**Comment by pointhi** [comment]
@evanshultz manage.sh is only a helper script for unix user. I don't know how python is used on windows (installing dependencies for example) but it should run on it without problems.
At least @SchrodingersGat is using the scripts on Windows.

**Comment by jensenr30** [comment]
@pointhi,
It is too difficult for me to get started using the KiCad footprint generator. I am trying to run the simpleFootprint.py script, but I am getting this error:
 ![image](https://user-images.githubusercontent.com/3083835/28488090-eb8e567a-6e67-11e7-9ea6-4165961bb025.png)
So now I am trying to install PyYAML, but PyYAML says that Python isn't installed on my machine (or it isn't right "right" version or something)
![image](https://user-images.githubusercontent.com/3083835/28488144-4b90fd92-6e69-11e7-94d6-c6cb83461ab4.png)
At this point, I'm not really motivated to try to get the footprint generator working on my machine because I already got the footprints looking nice and it wasn't simple to get the footprint generator working.

Also, I looked at the different scripts that were written. I was disappointed to see a lack of comments in the scripts. And each library seemed to have a totally different way of generating components! I was expecting to see something like a "capacitors_make.py", "resistors_make.py", "inductors_SMD_make.py", etc. in each directory, but instead it seemed like there were no conventions. Or, at least, I don't understand the organization method that is being used there...
![image](https://user-images.githubusercontent.com/3083835/28488171-19f63544-6e6a-11e7-8548-e4f1033e02c3.png)
![image](https://user-images.githubusercontent.com/3083835/28488172-224037d6-6e6a-11e7-804a-9a374614a16d.png)
![image](https://user-images.githubusercontent.com/3083835/28488173-2c850668-6e6a-11e7-96d9-6a8a78742095.png)


So either kicad-footprint-generator is not organized, or I'm stupid, or both.

If it was easy to get started and things were organized in a way I understood, I would be really excited to work within your footprint-generator framework! But I don't think it is, so I'm not really motivated to spend hours learning how to use it. 
:(
Sorry!
Jensen


@SchrodingersGat
@evanshultz

**Comment by SchrodingersGat** [comment]
Hi all, I run the scripts mostly on Windows (sometimes Linux). None of my scripts use yaml, although I have used it once. I installed this via pip on Windows.

@jensenr30 how did you try to install pyyaml?

**Comment by jensenr30** [comment]
@SchrodingersGat I found [this website](https://pypi.python.org/pypi/PyYAML) and installed this one:
![image](https://user-images.githubusercontent.com/3083835/28489195-592febb6-6e82-11e7-8f45-05f70f36baa3.png)
I had python 3.5.1 32 bit at the time. I even tried reinstalling python and updating to 3.6.

**Comment by pointhi** [comment]
@jensenr30 the scripts have no organisation yet (simply because it's only a collection of scripts made by differrent people, and I don't enforce rules on them yet. It's rare to work with them anyway at the moment).

The framework itself should be well structured, and has some functionalities added lately (which require yaml and csv support) which should help us to get more consistant script behaviour.

**Comment by evanshultz** [comment]
@jensenr30 For what it's worth, my trouble was that some scripts didn't just run simply and asked for YAML. Seems nothing to do with Windows. I explored a bit more and found other scripts that just ran. I exported the entire repo of https://github.com/pointhi/kicad-footprint-generator and was able to run eh_top_entry_tht.py straightaway. From there I was able to start modifying the script to make my own footprints. Perhaps give it a try using that script to see if you have success.

**Comment by poeschlr** [comment]
For most footprints this should be solved in the new repo. See: https://github.com/KiCad/kicad-footprints/pull/3

If there are still footprints left that need attention, please open a new issue over at the new repo. (This repo is declared legacy and will no longer accept pull requests.)
