### ISSUE TITLE
Library don't compliances to IPC-7351 for polarised caps

### ISSUE THREAD

**Issue by eldarkg** [KiCad/Capacitors_SMD.pretty#9]
- [ ] pin 1 (positive) should be on left side
- [ ] keys placed on pads in some parts

For e.g. c_elec_8x6.5.kicad_mod.
After production PCB boards keys will dissapear.

**Comment by SchrodingersGat** [comment]
Hi @eldarkg can you provide an example of you mean regarding point 2? 

I will try to work on point 1 - good catch.

**Comment by eldarkg** [comment]
@SchrodingersGat 
The symbol of plus on the first pad:
![plus on pad](https://cloud.githubusercontent.com/assets/5782069/17805814/0567762e-660a-11e6-83ca-58ce20a0e873.png)

**Comment by SchrodingersGat** [comment]
Oh right. Yes that is legitimately horrible. Do you feel like addressing this?

**Comment by eldarkg** [comment]
@SchrodingersGat I think the plus should be placed between the silk countur and coutyard upper of  first pad. And I don't know it is acceptable to place other silks on the pads.

**Comment by SchrodingersGat** [comment]
Agreed. They also need:

- [Outline placed on fabrication layer]
- [Polarization indicated on fabrication layer
- [Silkscreen removed from pads entirely]

**Comment by eldarkg** [comment]
@SchrodingersGat Silkscreen should contain the polarization too

**Comment by razykov** [comment]
[The proposed solution](https://github.com/KiCad/Capacitors_SMD.pretty/pull/11)

**Comment by eldarkg** [comment]
#11 Looks good

**Comment by eldarkg** [comment]
This seems as solved
